name: CI Pipeline

# Kapan robot ini bekerja?
# Jawab: Setiap ada 'push' ke branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  # Pekerjaan 1: Cek Kualitas Kode
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode dari repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
	run: |
	  python -m pip install --upgrade pip
	  pip install flake8
	  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Cek Kerapian Kode (Linting)
	# E501 abaikan error baris kepanjangan
	run: |
	  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
	  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # Pekerjaan 2: Cek Apakah Docker Bisa Dibuild
  docker-build-check:
    runs-on: ubuntu-latest
    needs: quality-check	# Hanya jalan kalau quality-check SUKSES
    steps:
      - name: Ambil kode
	uses: actions/checkout@v3

      - name: Coba Build Docker Image
	run: docker build . --file Dockerfile --tag my-app:test
